project_id = "ionrilzocengahkkgxdt"

[functions.send-email-notifications]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.send-auth-code]
verify_jwt = false

[functions.verify-auth-code]
verify_jwt = false
